import type { IResponseGetHelalGidaGuncellemePaketi } from "@scope/interface";
import { z } from "npm:zod";

// HdmListesi schema
const hdmListesiSchema = z.object({
  Id: z.number(),
  Adi: z.string(),
  AcikAdres: z.string(),
  MarketResimleri: z.string(),
  SorumluKisi: z.string().optional(),
  Telefon1: z.string().optional(),
  Telefon2: z.string().optional(),
  Koordinat: z.string().optional(),
  GuncellemeTarihi: z.string(),
  UlkeAd: z.string(),
  IlAd: z.string(),
  IlceAd: z.string(),
  SonDenetlemeTarihi: z.string(),
  DurumId: z.number(),
  AdresAciklama: z.string().optional(),
  SonDenetlemeRaporu: z.string().optional(),
});

// KategoriListesi schema
const kategoriListesiSchema = z.object({
  Id: z.number(),
  KategoriAdi: z.string(),
  SertifikaSayisi: z.number(),
});

// GecerliSertifikaListesi schema
const gecerliSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string().optional(),
  FirmaIletisimEmail: z.string().optional(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string().optional(),
  SertifikaNo: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  Durum: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  SertifikaResimleri: z.string().optional(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string().optional(),
  FirmaWebSayfasi: z.string().optional(),
  KapsamDisi: z.string().optional(),
  AskiyaAlmaAciklama: z.string().optional(),
  IptalAciklamasi: z.string().optional(),
});

// IptalEdilenSertifikaListesi schema
const iptalEdilenSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string(),
  FirmaWebSayfasi: z.string().optional(),
  FirmaIletisimEmail: z.string(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string(),
  SertifikaNo: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  Durum: z.string(),
  IptalAciklamasi: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string(),
  SertifikaResimleri: z.string().optional(),
  KapsamDisi: z.string().optional(),
  AskiyaAlmaAciklama: z.string().optional(),
});

// SuresiGecenSertifikaListesi schema
const suresiGecenSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string().optional(),
  FirmaWebSayfasi: z.string().optional(),
  FirmaIletisimEmail: z.string().optional(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string().optional(),
  SertifikaNo: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  Durum: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  SertifikaResimleri: z.string().optional(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string().optional(),
  KapsamDisi: z.string().optional(),
});

// YenilenmeyenFirmaSertifikaListesi schema
const yenilenmeyenFirmaSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string(),
  FirmaIletisimEmail: z.string(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  AskiyaAlmaAciklama: z.string(),
  Durum: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  SertifikaResimleri: z.string(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string(),
});

// AskiyaAlinanSertifikaListesi schema
const askiyaAlinanSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string(),
  FirmaIletisimEmail: z.string().optional(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string().optional(),
  SertifikaNo: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  KapsamDisi: z.string().optional(),
  Durum: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  SertifikaResimleri: z.string().optional(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string(),
  FirmaWebSayfasi: z.string().optional(),
});

// SonGuncellenenSertifikaListesi schema
const sonGuncellenenSertifikaListesiSchema = z.object({
  FirmaId: z.number(),
  FirmaAdi: z.string(),
  FirmaAdresi: z.string().optional(),
  FirmaTelefon: z.string().optional(),
  FirmaIletisimEmail: z.string().optional(),
  FirmaIl: z.string(),
  FirmaUlke: z.string(),
  SertifikaId: z.number(),
  KategoriId: z.number(),
  KategoriAdi: z.string(),
  MarkaAdi: z.string(),
  MarkaLogosu: z.string().optional(),
  SertifikaNo: z.string(),
  IlkSertifikaAlimTarihi: z.string(),
  SertifikaBitisTarihi: z.string(),
  YildizSayisi: z.number(),
  GuncellemeTarihi: z.string(),
  SertifikaKapsami: z.string(),
  Durum: z.string(),
  HanefiOk: z.boolean(),
  HanbeliOk: z.boolean(),
  SafiOk: z.boolean(),
  MalikiOk: z.boolean(),
  SertifikaResimleri: z.string().optional(),
  KapsamOnizleme: z.string(),
  Rozet: z.string(),
  BarkodluUrunSayisi: z.number(),
  Tarihce: z.string().optional(),
  FirmaWebSayfasi: z.string().optional(),
  KapsamDisi: z.string().optional(),
  AskiyaAlmaAciklama: z.string().optional(),
});

// Ana schema
const schema = z.object({
  HdmListesi: z.array(hdmListesiSchema),
  KategoriListesi: z.array(kategoriListesiSchema),
  GecerliSertifikaListesi: z.array(gecerliSertifikaListesiSchema),
  IptalEdilenSertifikaListesi: z.array(iptalEdilenSertifikaListesiSchema),
  SuresiGecenSertifikaListesi: z.array(suresiGecenSertifikaListesiSchema),
  YenilenmeyenFirmaSertifikaListesi: z.array(yenilenmeyenFirmaSertifikaListesiSchema),
  AskiyaAlinanSertifikaListesi: z.array(askiyaAlinanSertifikaListesiSchema),
  SonGuncellenenSertifikaListesi: z.array(sonGuncellenenSertifikaListesiSchema),
  BasvuruSurecindekiFirmaAdeti: z.number(),
});

export function isResponseValid(data: IResponseGetHelalGidaGuncellemePaketi): boolean {
  try {
    schema.parse(data);
    return true;
  } catch (error) {
    console.error("Veri validasyonu başarısız:", error);
    return false;
  }
}
